Repository getsentry/sentry-docs, pull requests merged in 2021-02, with the labels that each got.

#2998 feat: Docs for GA React Native Performance
  src/includes/performance/enable-tracing/react-native.mdx
  src/includes/performance/tracingOrigins-example/react-native.mdx
  src/platforms/common/performance/index.mdx
  src/platforms/react-native/performance/included-instrumentation.mdx
Labels: React-Native, performance

#2810 fix(native): Suggest release build
  src/includes/getting-started-install/native.mdx
Labels: Status: Accepted

#2693 ref(ui): use prism-sentry theme for code snippets
  package.json
  src/components/markdown.tsx
  src/css/_includes/code-blocks.scss
  src/css/screen.scss
  yarn.lock
Labels: Status: Accepted, Status: Stale

#2252 Add fnm as alternate node version manager in manual documentation
  src/docs/clients/react-native/manual-setup.mdx
Labels: Status: Stale

#2983 feat(apple): Enable sendDefaultPii
  src/platforms/common/configuration/options.mdx
Labels: Status: Stale
