Repository getsentry/sentry-docs, pull requests merged in 2021-06, with the labels that each got.

#3293 Drop `enable-tracing` property from Spring Boot integration docs.
  src/includes/performance/enable-tracing/java.spring-boot.mdx
  src/platforms/common/performance/index.mdx
Labels: Status: In Progress

#3553 PHP updates
  src/includes/enriching-events/set-context/php.mdx
  src/includes/enriching-events/user-feedback/example-widget/php.laravel.mdx
  src/includes/enriching-events/user-feedback/example-widget/php.mdx
  src/includes/sensitive-data/set-tag/php.mdx
  src/includes/sensitive-data/set-user/php.mdx
  src/includes/set-level/php.mdx
  src/includes/unset-user/php.mdx
Labels: Status: Stale

#3701 restructure Search content
  src/docs/product/issues/index.mdx
  src/docs/product/sentry-basics/search/index.mdx
  src/docs/product/sentry-basics/search/saved-searches.mdx
  src/docs/product/sentry-basics/search/searchable-properties.mdx
Labels: Product Docs

#3730 feat: Add Installation Guide for @sentry/capacitor
  src/includes/getting-started-config/capacitor.mdx
  src/includes/getting-started-config/javascript.capacitor.mdx
  src/includes/getting-started-install/javascript.capacitor.mdx
  src/includes/getting-started-primer/javascript.capacitor.mdx
  src/includes/getting-started-verify/capacitor.mdx
  src/includes/getting-started-verify/javascript.capacitor.mdx
  src/platforms/common/configuration/sampling.mdx
  src/platforms/javascript/common/install/index.mdx
  src/platforms/javascript/guides/capacitor/config.yml
Labels: Platform: Capacitor

#3596 Install of sentry cli in pipeline must return true
  src/docs/product/releases/setup/release-automation/jenkins/index.mdx
Labels: Status: Stale

#3757 Clarify disabling auto session tracking on React Native
  src/includes/configuration/auto-session-tracking/react-native.mdx
Labels: Team: Mobile Platform

#3627 React Updates
  src/docs/clients/javascript/integrations.mdx
  src/docs/contributing/pages/index.mdx
  src/docs/product/performance/getting-started.mdx
  src/includes/capture-error/javascript.react.mdx
  src/includes/configuration/capture-console/javascript.mdx
  src/includes/configuration/debug/javascript.mdx
  src/includes/configuration/dedupe/javascript.mdx
  src/includes/configuration/enable-pluggable-integrations/javascript.mdx
  src/includes/configuration/extra-error-data/javascript.mdx
  src/includes/configuration/offline/javascript.mdx
  src/includes/configuration/reporting-observer/javascript.mdx
  src/includes/configuration/rewrite-frames/javascript.mdx
  src/includes/getting-started-config/javascript.react.mdx
  src/includes/getting-started-install/javascript.react.mdx
  src/includes/getting-started-primer/javascript.react.mdx
  src/includes/getting-started-verify/javascript.react.mdx
  src/includes/performance/enable-tracing/javascript.mdx
  src/platforms/common/performance/index.mdx
  src/platforms/javascript/guides/react/components/errorboundary.mdx
  src/platforms/javascript/guides/react/components/profiler.mdx
  src/platforms/javascript/guides/react/config.yml
  src/platforms/javascript/guides/react/configuration/integrations/index.mdx
  src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
  src/platforms/javascript/guides/react/configuration/integrations/redux.mdx
  src/platforms/javascript/guides/react/index.mdx
  src/platforms/react-native/touchevents.mdx
  src/wizard/javascript/react.md
Labels: Status: In Progress, Team: Web Platform
