Repository getsentry/sentry-docs, pull requests merged in 2022-07, with the labels that each got.

#5057 Dotnet tunnel docs
  src/platforms/dotnet/guides/aspnetcore/index.mdx
Labels: Status: Stale

#5283 fix(native): clean up install/build instructions
  src/includes/getting-started-install/native.mdx
  src/includes/getting-started-install/native.qt.mdx
Labels: Status: In Progress

#5339 fix(python): Clarify which Celery signals work and explain Celery + Django setup
  src/platforms/python/guides/celery/index.mdx
Labels: Platform: Python, Team: Web Backend

#5329 Docs for Starlette and FastAPI integration.
  package.json
  src/platforms/python/guides/fastapi/index.mdx
  src/platforms/python/guides/starlette/index.mdx
  src/wizard/python/fastapi.md
  src/wizard/python/starlette.md
  yarn.lock
Labels: Platform: Python, Team: Web Backend

#5224 add metrics content
  src/docs/product/dashboards/widget-builder/index.mdx
  src/docs/product/sentry-basics/key-terms.mdx
  src/docs/product/sentry-basics/metrics/index.mdx
  src/docs/product/sentry-basics/metrics/metrics-events-subsets.png
  src/docs/product/sentry-basics/search/searchable-properties.mdx
Labels: Status: In Progress
