Repository getsentry/sentry-docs, pull requests merged in 2022-01, with the labels that each got.

#4444 Add documentation for Quart based on the sanic documentation
  src/platforms/python/guides/quart/index.mdx
  src/wizard/python/quart.md
Labels: Status: In Progress

#4485 Update triage link to point to triage section
  src/docs/product/issues/index.mdx
Labels: Status: Stale

#4511 react-native: perf auto instr
  src/platforms/react-native/performance/instrumentation/automatic-instrumentation.mdx
Labels: Status: In Progress

#4606 feat(apple): Add SwiftUI init to wizard
  src/wizard/apple/ios.md
  src/wizard/apple/macos.md
Labels: Platform: Cocoa

#4604 ref(apple): Move warning for min 7.x to migration
  src/platforms/apple/common/migration.mdx
  src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Labels: Platform: Cocoa

#4605 feat(apple): How to init SDK when using SwiftUI
  src/includes/getting-started-config/apple.mdx
Labels: Platform: Cocoa

#4455 docs(suspect-spans): Add documentation for suspect spans
  src/docs/product/performance/exclusive-time.png
  src/docs/product/performance/transaction-summary.mdx
Labels: Status: In Progress

#4607 ref(apple): Mention other install methods sooner
  src/includes/getting-started-install/apple.ios.mdx
  src/includes/getting-started-install/apple.macos.mdx
  src/includes/getting-started-install/apple.mdx
  src/includes/getting-started-install/apple.tvos.mdx
  src/includes/getting-started-install/apple.watchos.mdx
  src/wizard/apple/index.md
  src/wizard/apple/ios.md
  src/wizard/apple/macos.md
Labels: Platform: Cocoa

#4528 add 429 behaviour explanation
  src/docs/product/accounts/quotas/index.mdx
Labels: Status: In Progress

#4474 Update BrowserTracing import for tree shaking
  src/includes/getting-started-config/javascript.angular.mdx
  src/includes/getting-started-config/javascript.mdx
  src/includes/getting-started-config/javascript.react.mdx
  src/includes/getting-started-config/javascript.vue.mdx
  src/includes/performance/beforeNavigate-example/javascript.mdx
  src/includes/performance/beforeNavigate-example/javascript.nextjs.mdx
  src/includes/performance/configure-sample-rate/javascript.mdx
  src/includes/performance/configure-sample-rate/javascript.react.mdx
  src/includes/performance/configure-sample-rate/javascript.vue.mdx
  src/includes/performance/enable-automatic-instrumentation/javascript.mdx
  src/includes/performance/enable-automatic-instrumentation/javascript.react.mdx
  src/includes/performance/filter-span-example/javascript.mdx
  src/includes/performance/filter-span-example/javascript.nextjs.mdx
  src/includes/performance/group-transaction-example/javascript.mdx
  src/includes/performance/tracingOrigins-example/javascript.mdx
  src/includes/performance/tracingOrigins-example/javascript.nextjs.mdx
  src/platforms/javascript/common/configuration/integrations/custom.mdx
  src/platforms/javascript/common/install/cdn.mdx
  src/platforms/javascript/common/performance/instrumentation/automatic-instrumentation.mdx
  src/platforms/javascript/guides/react/configuration/integrations/react-router.mdx
  src/platforms/javascript/guides/vue/configuration/integrations/vue-router.mdx
  src/platforms/node/common/configuration/integrations/index.mdx
  src/wizard/capacitor/index.md
  src/wizard/javascript/angular.md
  src/wizard/javascript/angularjs.md
  src/wizard/javascript/backbone.md
  src/wizard/javascript/browser.md
  src/wizard/javascript/index.md
  src/wizard/javascript/react.md
  src/wizard/javascript/vue.md
Labels: Status: In Progress
