Repository getsentry/sentry-docs, pull requests merged in 2022-03, with the labels that each got.

#4646 feat(apple): No OOM tracking for unit tests
  src/platforms/apple/common/configuration/out-of-memory.mdx
Labels: Status: Backlog

#4783 feat(apple): Clarify why OOMs don't have much context
  src/platforms/apple/common/configuration/out-of-memory.mdx
Labels: Platform: Cocoa

#4647 docs: clarify message filtering
  src/docs/product/accounts/quotas/index.mdx
  src/docs/product/data-management-settings/filtering/index.mdx
Labels: Status: In Progress

#4704 chore(android): Mention that Timber.tag is not supported
  src/platforms/android/configuration/integrations/timber.mdx
  src/platforms/android/migration.mdx
Labels: Status: In Progress

#4766 feat(RN): Touch event boundary now take a sentry-label prop
  src/platforms/react-native/touchevents.mdx
Labels: Status: Stale

#4864 fix(py): Clean up webhook snippets
  src/docs/product/integrations/integration-platform/webhooks.mdx
Labels: Team: Ecosystem
