Repository getsentry/sentry-docs, pull requests merged in 2023-01, with the labels that each got.

#5919 fix(apple): Delete experimental note GA features
  src/platform-includes/getting-started-primer/apple.mdx
  src/platforms/apple/common/configuration/swizzling.mdx
  src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
Labels: Status: Stale

#5939 feat(apple): Migration guide for sentry-cocoa 7 -> 8
  src/platforms/apple/common/migration.mdx
Labels: Status: Stale, Status: Backlog

#5938 feat(apple): Rename the OOM integration
  src/platforms/apple/common/configuration/integrations/default.mdx
  src/platforms/apple/common/configuration/out-of-memory.mdx
  src/platforms/apple/common/configuration/watchdog-terminations.mdx
Labels: Status: Backlog

#5859 ref(apple): Rename APM tracking feature flags to tracing
  src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
  src/wizard/apple/ios.md
Labels: Status: Backlog

#6059 fix(apple): Renamings from tracking to tracing
  src/platform-includes/getting-started-config/apple.mdx
  src/platform-includes/getting-started-primer/apple.mdx
  src/platforms/apple/common/configuration/swizzling.mdx
  src/platforms/apple/common/performance/instrumentation/automatic-instrumentation.mdx
  src/wizard/apple/ios.md
Labels: Platform: Cocoa

#5455 Update hermes docs to use bundled hermesc script
  src/platforms/react-native/manual-setup/hermes.mdx
Labels: Status: Backlog, Platform: React-Native

#6111 updating with otel google group
  src/includes/beta-note-opentelemetry.mdx
  src/platforms/java/common/performance/instrumentation/opentelemetry.mdx
Labels: performance

#6165 Remove `\` before $
  src/docs/product/sentry-basics/migration/index.mdx
Labels: Common content, Team: Web SDK Backend

#6019 Add docs for `traceOptionsRequests`
  src/platforms/common/configuration/options.mdx
Labels: Status: In Progress

#6189 ref: Fix transaction ops examples
  src/platform-includes/performance/enable-manual-instrumentation/php.mdx
  src/platform-includes/performance/retrieve-transaction/php.mdx
Labels: Platform: PHP, Team: Web SDK Backend
