Repository getsentry/sentry-docs, pull requests merged in 2024-04, with the labels that each got.

#9289 Add a section on debugging symbol files
  docs/platforms/dotnet/common/data-management/debug-files/symbol-servers/index.mdx
Labels: Stale

#9634 Symfony SDK 5.0.0
  docs/platforms/php/common/configuration/options.mdx
  docs/platforms/php/guides/symfony/configuration/symfony-options.mdx
  docs/platforms/php/guides/symfony/index.mdx
  docs/platforms/php/guides/symfony/metrics/index.mdx
Labels: Platform: PHP, Team: Web Backend SDKs, Product Area: SDKs - Web Backend

#9334 Add documentation for performance v2
  docs/platforms/android/performance/instrumentation/perf-v2.mdx
  docs/product/performance/mobile-vitals/app-starts.mdx
  platform-includes/getting-started-primer/android.mdx
  public/platforms/android/performance/instrumentation/perf-v2-app-start.png
  public/platforms/android/performance/instrumentation/perf-v2-frame-delay.png
Labels: Stale

#9167 feat: Fix contribution docs
  .env.example
  CONTRIBUTING.md
  package.json
  prisma/seed/seed.mjs
  src/components/changelog/list.tsx
  yarn.lock
Labels: Stale

#9526 Document new configuration option
  docs/platforms/javascript/common/user-feedback/configuration/index.mdx
Labels: Stale

#9181 feat(flutter): isar integration
  docs/platforms/flutter/integrations/isar-instrumentation.mdx
Labels: Stale

#9335 ref(angular): Update Nx CLI source maps upload guide for esbuild
  docs/platforms/javascript/common/sourcemaps/uploading/angular-nx.mdx
Labels: WIP

#9769 Remove mention of setting up a monitor in the UI
  platform-includes/crons/requirements/php.laravel.mdx
Labels: Platform: PHP, Team: Web Backend SDKs, Product Area: SDKs - Web Backend

#9674 Add documentation about new Laravel spans
  docs/platforms/php/guides/laravel/performance/instrumentation/automatic-instrumentation.mdx
Labels: Platform: PHP, Team: Web Backend SDKs, Product Area: SDKs - Web Backend

#9576 feat(app-start): Add section for eligible span ops
  docs/product/performance/mobile-vitals/app-starts.mdx
Labels: Stale

#9777 Document `before_send_check_in`
  docs/platforms/php/common/configuration/filtering.mdx
  docs/platforms/php/common/configuration/options.mdx
  platform-includes/configuration/before-send-check-in/php.laravel.mdx
  platform-includes/configuration/before-send-check-in/php.mdx
  platform-includes/configuration/before-send-check-in/php.symfony.mdx
Labels: Platform: PHP, Team: Web Backend SDKs, Product Area: SDKs - Web Backend
