Repository getsentry/sentry-docs, pull requests merged in 2024-06, with the labels that each got.

#10213 Add insights page
  docs/product/insights/index.mdx
Labels: Launch 🚀

#10273 Move insights
  docs/concepts/search/searchable-properties/events.mdx
  docs/platforms/android/tracing/instrumentation/automatic-instrumentation.mdx
  docs/platforms/android/tracing/instrumentation/perf-v2.mdx
  docs/platforms/apple/common/tracing/instrumentation/automatic-instrumentation.mdx
  docs/platforms/flutter/tracing/instrumentation/automatic-instrumentation.mdx
  docs/platforms/javascript/common/tracing/instrumentation/automatic-instrumentation.mdx
  docs/platforms/javascript/common/tracing/instrumentation/custom-instrumentation/requests-module.mdx
  docs/platforms/python/integrations/anthropic/index.mdx
  docs/platforms/python/integrations/cohere/index.mdx
  docs/platforms/python/integrations/huggingface_hub/index.mdx
  docs/platforms/python/integrations/openai/index.mdx
  docs/platforms/python/tracing/instrumentation/custom-instrumentation/requests-module.mdx
  docs/platforms/react-native/tracing/instrumentation/automatic-instrumentation.mdx
  docs/platforms/react-native/tracing/instrumentation/time-to-display.mdx
  docs/product/explore/profiling/mobile-app-profiling/metrics.mdx
  docs/product/explore/session-replay/replay-details.mdx
  docs/product/index.mdx
  docs/product/insights/assets.mdx
  docs/product/insights/caches/cache-page.mdx
  docs/product/insights/caches/index.mdx
  docs/product/insights/img/asset-sample-images.png
  docs/product/insights/img/diagram-transaction-cls.png
  docs/product/insights/img/diagram-transaction-vitals.png
  docs/product/insights/img/query-source-laravel.png
  docs/product/insights/llm-monitoring/getting-started/index.mdx
  docs/product/insights/llm-monitoring/getting-started/the-dashboard.mdx
  docs/product/insights/llm-monitoring/img/details-view.png
  docs/product/insights/llm-monitoring/img/pipelines-view.png
  docs/product/insights/llm-monitoring/img/trace-view.png
  docs/product/insights/llm-monitoring/index.mdx
  docs/product/insights/mobile-vitals/app-starts.mdx
  docs/product/insights/mobile-vitals/img/01_full_widget_mobile.png
  docs/product/insights/mobile-vitals/img/app-start-transaction.png
  docs/product/insights/mobile-vitals/img/app-starts-samples-by-event.png
  docs/product/insights/mobile-vitals/img/app-starts-screen-summary.png
  docs/product/insights/mobile-vitals/img/app-starts-span-detail-view.png
  docs/product/insights/mobile-vitals/img/app-starts.png
  docs/product/insights/mobile-vitals/img/screen-loads-screen-summary.png
  docs/product/insights/mobile-vitals/img/screen-loads-span-detail.png
  docs/product/insights/mobile-vitals/img/screen-loads.png
  docs/product/insights/mobile-vitals/img/slow-frozen-frames.png
  docs/product/insights/mobile-vitals/img/time-to-initial-full-display.png
  docs/product/insights/mobile-vitals/img/ttid-ttfd-affecting-spans.png
  docs/product/insights/mobile-vitals/index.mdx
  docs/product/insights/mobile-vitals/screen-loads.mdx
  docs/product/insights/queries.mdx
  docs/product/insights/queue-monitoring/index.mdx
  docs/product/insights/queue-monitoring/queues-page.mdx
  docs/product/insights/requests.mdx
  docs/product/insights/web-vitals/index.mdx
  docs/product/insights/web-vitals/web-vitals-concepts.mdx
  docs/product/issues/issue-details/performance-issues/large-render-blocking-asset/index.mdx
  docs/product/performance/filters-display/index.mdx
  docs/product/performance/filters-display/widgets.mdx
  docs/product/performance/index.mdx
  docs/product/performance/metrics.mdx
  docs/product/performance/transaction-summary.mdx
  platform-includes/getting-started-primer/basic-features/apple.mdx
  src/middleware.ts
Labels: Launch 🚀

#10263 Python Insights modules links
  docs/platforms/python/tracing/instrumentation/custom-instrumentation/caches-module.mdx
  docs/platforms/python/tracing/instrumentation/custom-instrumentation/queues-module.mdx
  docs/platforms/python/tracing/instrumentation/custom-instrumentation/requests-module.mdx
Labels: Effort: Small, Product Area: Performance, Launch 🚀

#10283 Metrics beta change disclaimer
  docs/product/metrics/index.mdx
  includes/metrics-api-change.mdx
Labels: Launch 🚀

#10229 Update billing quota pages for AM3
  docs/pricing/quotas/index.mdx
  docs/pricing/quotas/manage-attachments-quota.mdx
  docs/pricing/quotas/manage-cron-monitors.mdx
  docs/pricing/quotas/manage-event-stream-guide.mdx
  docs/pricing/quotas/manage-replay-quota.mdx
  docs/pricing/quotas/manage-transaction-quota.mdx
  docs/pricing/quotas/spike-protection.mdx
Labels: Launch 🚀

#10278 update arcades for insights
  docs/product/insights/assets.mdx
  docs/product/insights/caches/cache-page.mdx
  docs/product/insights/caches/index.mdx
  docs/product/insights/llm-monitoring/index.mdx
  docs/product/insights/mobile-vitals/app-starts.mdx
  docs/product/insights/mobile-vitals/index.mdx
  docs/product/insights/mobile-vitals/screen-loads.mdx
  docs/product/insights/queries.mdx
  docs/product/insights/queue-monitoring/index.mdx
  docs/product/insights/queue-monitoring/queues-page.mdx
  docs/product/insights/requests.mdx
  docs/product/insights/web-vitals/index.mdx
Labels: Launch 🚀

#10049 Fix: Outline button variant style fixes in changelog.
  src/components/changelog/ui/Button/index.tsx
Labels: Stale

#10246 feat(tracing): Update spans section
  docs/concepts/key-terms/tracing/distributed-tracing.mdx
Labels: Launch 🚀

#10210 Update billing docs for AM3
  docs/pricing/img/product-trial-pop-up-in-sentry-ui.png
  docs/pricing/index.mdx
Labels: Launch 🚀

#10244 feat(.NET): Added new onboarding
  docs/platforms/dotnet/guides/aspnet/index.mdx
  docs/platforms/dotnet/guides/aspnetcore/index.mdx
  docs/platforms/dotnet/guides/aws-lambda/index.mdx
  docs/platforms/dotnet/guides/azure-functions-worker/index.mdx
  docs/platforms/dotnet/guides/entityframework/index.mdx
  docs/platforms/dotnet/guides/extensions-logging/index.mdx
  docs/platforms/dotnet/guides/google-cloud-functions/index.mdx
  docs/platforms/dotnet/guides/log4net/index.mdx
  docs/platforms/dotnet/guides/maui/index.mdx
  docs/platforms/dotnet/guides/nlog/index.mdx
  docs/platforms/dotnet/guides/serilog/index.mdx
  docs/platforms/dotnet/guides/uwp/index.mdx
  docs/platforms/dotnet/guides/winforms/index.mdx
  docs/platforms/dotnet/guides/winui/index.mdx
  docs/platforms/dotnet/guides/wpf/index.mdx
  docs/platforms/dotnet/index.mdx
Labels: Launch 🚀

#10224 docs(traces): Add traces product doc page
  docs/product/explore/traces/img/traces-multiple-span-conditions-example.png
  docs/product/explore/traces/img/traces-one-span-conditions-example.png
  docs/product/explore/traces/img/traces-results.png
  docs/product/explore/traces/index.mdx
Labels: Launch 🚀

#10318 update concepts docs
  docs/concepts/key-terms/key-terms.mdx
  docs/product/index.mdx
  docs/product/sentry-basics/index.mdx
Labels: Launch 🚀

#10346 update trace explorer nav order
  docs/product/explore/traces/index.mdx
Labels: Launch 🚀

#10327 feat(tracing): Add searchable span properties
  docs/concepts/search/searchable-properties/events.mdx
  docs/concepts/search/searchable-properties/index.mdx
  docs/concepts/search/searchable-properties/spans.mdx
Labels: Launch 🚀

#10339 Created Metrics Settings Page
  docs/product/explore/metrics/img/metric-details.png
  docs/product/explore/metrics/img/metric-settings-query.png
  docs/product/explore/metrics/img/metric-settings.png
  docs/product/explore/metrics/metrics-settings.mdx
Labels: Launch 🚀

#10290 feat(Android): update getting started and feature pages
  docs/platforms/android/features/index.mdx
  docs/platforms/android/index.mdx
  platform-includes/getting-started-config/android.mdx
  platform-includes/getting-started-install/android.mdx
  platform-includes/getting-started-primer/android.mdx
  platform-includes/getting-started-verify/android.mdx
Labels: Platform: Android

#10079 Remove reference to deprecated "Sentry as a Container Image"
  docs/platforms/javascript/guides/aws-lambda/index.mdx
Labels: Stale

#10453 Small fix in code snippet
  docs/product/insights/llm-monitoring/getting-started/index.mdx
Labels: Platform: Python, Effort: Small

#10199 fix snippet
  docs/platforms/react-native/migration/sentry-expo.mdx
Labels: Stale

#10203 add okhttp client error java examples
  docs/platforms/android/integrations/okhttp/index.mdx
Labels: Stale

#10158 fix(ruby): Use new meta helper in rails view
  platform-includes/distributed-tracing/custom-instrumentation/ruby.mdx
Labels: WIP

#10489 fix(python): Fix typo, capitalization in Spark integration
  docs/platforms/python/integrations/spark/index.mdx
Labels: Effort: Small

#10523 Python/Starlette: Added new config option
  docs/platforms/python/integrations/starlette/index.mdx
Labels: Platform: Python, Effort: Small
