Repository getsentry/sentry-docs, pull requests merged in 2024-11, with the labels that each got.

#11370 Add documentation for instrumenting cache with Go
  docs/platforms/go/common/tracing/instrumentation/caches-module.mdx
Labels: wip

#11360 Add Integrations page for Go
  docs/platforms/go/common/integrations/index.mdx
Labels: Platform: Go, wip

#11158 ref(alerts): Add docs for dynamic alerts
  docs/organization/early-adopter-features/index.mdx
  docs/product/alerts/alert-types.mdx
  docs/product/alerts/create-alerts/img/dynamic-threshold.png
  docs/product/alerts/create-alerts/metric-alert-config.mdx
Labels: wip

#11940 docs(sdks): Span Sampling
  develop-docs/sdk/telemetry/spans/filtering.mdx
  develop-docs/sdk/telemetry/spans/index.mdx
  develop-docs/sdk/telemetry/spans/sampling.mdx
  develop-docs/sdk/telemetry/spans/scrubbing-data.mdx
Labels: All SDKs
