Repository getsentry/sentry-docs, pull requests merged in 2024-01, with the labels that each got.

#8606 Note on bindToScope in Apple/Cocoa custom instr.
  src/platform-includes/performance/create-transaction-bound-to-scope/apple.mdx
Labels: Stale

#8605 Note on bindToScope in Java custom instr.
  src/platform-includes/performance/create-transaction-bound-to-scope/java.mdx
Labels: Stale

#8614 fix: Missing multi-line terminator for bash command
  src/platforms/react-native/sourcemaps/index.mdx
Labels: Stale

#8657 feat(profiling): add differential flamegraph docs
  src/docs/product/profiling/differential-flamegraph-inverted.png
  src/docs/product/profiling/differential-flamegraph-new.png
  src/docs/product/profiling/differential-flamegraph-regular.png
  src/docs/product/profiling/differential-flamegraph-table.png
  src/docs/product/profiling/differential-flamegraph.png
  src/docs/product/profiling/differential-flamegraphs.mdx
Labels: Stale

#8924 Update docs for PHP SDK 4.4.0
  src/platform-includes/crons/setup/php.mdx
  src/platform-includes/performance/add-spans-example/php.mdx
  src/platform-includes/performance/enable-manual-instrumentation/php.mdx
  src/platform-includes/performance/retrieve-transaction/php.mdx
Labels: Platform: PHP, Product Area: SDKs - Web Backend

#8972 Add PHP Metrics docs
  src/platforms/php/common/metrics/index.mdx
Labels: Platform: PHP

#8978 Add Laravel Metrics docs
  src/platforms/php/guides/laravel/metrics/index.mdx
Labels: Platform: PHP
