Repository getsentry/sentry-docs, pull requests merged in 2024-05, with the labels that each got.

#9373 feat: Format code blocks at build time
  package.json
  src/mdx.ts
  src/remark-format-code.js
  yarn.lock
Labels: Stale

#9666 Update deprecated option names and attachStacktrace value
  docs/platforms/react-native/configuration/options.mdx
Labels: Stale

#9756 Update description for Investigation Mode
  docs/product/performance/retention-priorities/index.mdx
Labels: Stale

#9732 docs(priority-alerts): Add docs for high priority alert conditions
  docs/product/alerts/best-practices.mdx
  docs/product/alerts/create-alerts/issue-alert-config.mdx
Labels: Stale

#9343 ref(v8/sveltekit): Adjust manual setup for Vite plugin 2.x bump
  docs/platforms/javascript/guides/sveltekit/manual-setup.mdx
  platform-includes/getting-started-verify/javascript.sveltekit.mdx
  platform-includes/sourcemaps/primer/javascript.sveltekit.mdx
Labels: WIP

#10100 [Python] Smaller changes
  docs/platforms/python/integrations/index.mdx
  docs/platforms/python/integrations/redis/index.mdx
  docs/platforms/python/performance/instrumentation/custom-instrumentation/cache-module.mdx
Labels: Platform: Python, Effort: Small, Product Area: Performance

#10101 [Python] Guide for Manual Queues Insights Module Instrumenation
  docs/platforms/python/performance/instrumentation/custom-instrumentation/caches-module.mdx
  docs/platforms/python/performance/instrumentation/custom-instrumentation/queues-module.mdx
Labels: Platform: Python, Effort: Medium, Product Area: Performance

#10104 [Python] New `cache_prefixes` config param for `RedisInstegration`.
  docs/platforms/python/integrations/redis/index.mdx
Labels: Platform: Python, Effort: Small, Product Area: Performance

#10161 Small update to distributed tracing in Celery
  docs/platforms/python/integrations/celery/index.mdx
Labels: Platform: Python, Effort: Small
