Repository getsentry/sentry-docs, pull requests merged in 2025-01, with the labels that each got.

#12081 Consistently use `wrapCreateBrowserRouterV6` on V6 page
  docs/platforms/javascript/guides/react/features/react-router/v6.mdx
Labels: Stale

#12267 Remove Go profiling docs
  docs/platforms/go/common/profiling/index.mdx
  docs/platforms/go/common/profiling/troubleshooting/index.mdx
  docs/product/explore/profiling/getting-started.mdx
  docs/product/explore/profiling/index.mdx
Labels: Product Area: SDKs - Web Backend

#12268 Document how to attach data attributes onto a span/transaction in PHP
  docs/platforms/php/common/tracing/instrumentation/custom-instrumentation.mdx
Labels: Team: Web SDK Backend

#12276 [Python ]Add span `set_data` docs
  docs/platforms/python/tracing/instrumentation/custom-instrumentation/index.mdx
Labels: Platform: Python, Effort: Small

#12167 docs(astro): fix typo
  platform-includes/sourcemaps/overview/javascript.astro.mdx
Labels: Stale

#12210 ref(self-hosted): Update docs for GeoIP update and `dc up -d`
  develop-docs/self-hosted/geolocation.mdx
  develop-docs/self-hosted/index.mdx
  develop-docs/self-hosted/releases.mdx
  develop-docs/self-hosted/troubleshooting/kafka.mdx
Labels: Stale

#12375 Clean up Symfony options
  docs/platforms/php/common/configuration/options.mdx
  docs/platforms/php/guides/symfony/configuration/symfony-options.mdx
Labels: Product Area: SDKs - Web Backend

#12434 Add missing Laravel Crons parameters
  platform-includes/crons/setup/php.laravel.mdx
Labels: Platform: PHP, Product Area: SDKs - Web Backend

#12110 feat(platform): Add image cards to devdocs getting started page
  develop-docs/getting-started/index.mdx
  src/components/card.tsx
  src/components/devDocsCardGrid.tsx
  src/components/docPage/type.scss
  src/imgs/back-end.png
  src/imgs/dev-infra.png
  src/imgs/front-end.png
  src/imgs/ingest.png
  src/imgs/integrate.png
  src/imgs/sdks.png
  src/imgs/services.png
  src/mdxComponents.ts
Labels: Develop
